---
# tasks file for wordpress

- name: Download WordPress
  get_url:
    url: https://wordpress.org/wordpress-latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz
  become: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress-latest.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  become: yes

- name: Move WordPress install files
  command: mv /tmp/wordpress /var/www/
  become: yes

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"

- name: Update WordPress config file
  lineinfile:
    dest: "/var/www/wordpress/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'mysql');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'root');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'root');"}
  become: yes

- name: Restart Apache2
  become: yes
  service:
    name: apache2
    state: restarted
