---
- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
  become: yes
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
  become: yes
- name: Install MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user="{{ MYSQL_user }}"
  become: yes
- name: Secures the MySQL root user
  become: yes
  mysql_user: user="{{ MYSQL_user }}" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user="{{ MYSQL_user }}"
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user="{{ MYSQL_user }}"
  become: yes
