---
- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
  become: yes
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
  become: yes
- name: Install MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_os_family == 'Debian'
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user="{{ MYSQL_user }}"
  become: yes
- name: Secures the MySQL root user
  become: yes
  mysql_user: user="{{ MYSQL_user }}" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user="{{ MYSQL_user }}"
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user="{{ MYSQL_user }}"
  become: yes

- name: debconf for PhpMyAdmin
  become: yes
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for PhpMyAdmin
  become: yes
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{MySQL_root_pass}}' vtype='password'

- name: debconf for PhpMyAdmin
  become: yes
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{MySQL_root_pass}}' vtype='password'

- name: debconf for PhpMyAdmin
  become: yes
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{MySQL_root_pass}}' vtype='password'

- name: debconf for PhpMyAdmin
  become: yes
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='apache2' vtype='multiselect'

- name: install PhpMyAdmin
  become: yes
  apt: pkg=phpmyadmin state=present

- name: apache2 restart
  become: yes
  command: systemctl restart apache2

- name: Copy PHP Conf to Apache2
  become: yes
  command: cp /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyad$

- name: Continue with PHP MyAdmin Setup
  become: yes
  command: a2enconf phpmyadmin

- name: ensure apache is running
  service:
    name: apache2
    state: started
