---
# add php repository
- name: add php repository
  ignore_errors: True
  shell: sudo apt-add-repository -y ppa:ondrej/php

# Install Apache for wordpress_server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install Required Software
  apt: name={{ item }} state=present
  become: yes
  with_items: 
    - apache2
    - mysql-server
    - php7.0-mysql
    - php7.0
    - libapache2-mod-php7.0
    - python-mysqldb

